### ISSUE TITLE
Axios

### ISSUE THREAD

**Issue by IVKLD** [JoCat/beautiful-listing#1]
Как можно реализовать POST, чтобы получить список серверов в виде json?

**Comment by JoCat** [comment]
Боюсь что никак, стандартные листинги не имеют такой фичи. Если юзать fancyindex, можно получать файлы в json вместо html. Но тогда листинг нужно переделать немножко.

А так можно получать запросом страничку и через парсинг контента доставать инфу.

**Comment by JoCat** [comment]
Например так:

```js
const response = await axios.get('https://storage.aurora-launcher.ru/launcherserver/0.0.3/');

const parser = new DOMParser();
const content = parser.parseFromString(response.data, "text/html");

const links = [...content.querySelectorAll('.link a')];

const result = links
    .filter(link => link.title.length > 0) // Убираем первую ссылку, которая введёт на уровень выше
    .map(link => ({title: link.title, link: link.href}));
```

**Comment by IVKLD** [comment]
Спасибо

**Comment by IVKLD** [comment]
> 

Я получаю "Длину 0" от такого скрипта. Использую vue.

**Comment by JoCat** [comment]
Код в студию)

**Comment by IVKLD** [comment]
![image](https://user-images.githubusercontent.com/54883747/195355653-6c3a6fd6-517d-4edb-9705-e1aa2e257a7b.png)
![image](https://user-images.githubusercontent.com/54883747/195358460-269131cd-bf6a-40dc-a256-e7f5b7af6cf3.png)

**Comment by JoCat** [comment]
Ну и зачем ты await убрал?

**Comment by IgnIVertiKalCaD** [comment]
![image](https://user-images.githubusercontent.com/54883747/195373742-29b8c7f3-e000-486e-9767-3d55570fa6b7.png)
Вот с ним

**Comment by IVKLD** [comment]
![image](https://user-images.githubusercontent.com/54883747/195373947-fdf44159-31da-4f57-bb01-876f0b762831.png)
Вот с ним

**Comment by JoCat** [comment]
А ну да, в твоём случае такой вариант не сработает

**Comment by JoCat** [comment]
В твоём случае код будет такой:

```js
const link = 'https://mirror-sky.xyz/Gravit5.2.9%2B/server/1.7.10/' // Слеш на конце обязателен
const response = await axios.get(link);

const parser = new DOMParser();
const content = parser.parseFromString(response.data, "text/html");

const links = [...content
    .querySelector("pre")
    .innerHTML.matchAll(
      /<a href="(.+(\.[\w]{2,4}|\/))">(.+)<\/a>\s+([\w-]+\s[\d:]+)\s+([\d]+[K|M]?|-)/g
    )
];

const result = links.map(_link => ({title: _link[3], link: link + _link[1]}));
```

**Comment by JoCat** [comment]
Думаю можно даже так поменять, если используешь `@nuxtjs/axios`:

```js
const data = await axios.$get(link);

const parser = new DOMParser();
const content = parser.parseFromString(data, "text/html");
```

**Comment by IVKLD** [comment]
> 
Воркает, спасиб
Сейчас ещё один вопрос сделаю
