### ISSUE TITLE
Nginx and async download

### ISSUE THREAD

**Issue by IVKLD** [JoCat/beautiful-listing#2]
Как сделать, чтобы при скачивании с облака, можно было переходить в другие диррективы. В моём случае виснет и, пока не скачается файл, нельзя перемещаться.

Конфиг nginx:
`server {
        listen 80 default_server;
        listen [::]:80 default_server;

        index index.html index.htm index.nginx-debian.html;

        server_name mirror-sky.xyz;

        location / {
        root /var/www/mirror;
        add_header 'Access-Control-Allow-Origin' '*';
    autoindex on; # �������� ����� ��������� ������
    autoindex_localtime on; # ������� ����� � �������� �������� � ��������� ��������� ����
    autoindex_exact_size off; # ��������� ������� ������ � �������� �������� �� ��������, �������� � ��������
    sub_filter '<html>' ''; # ������� � ������� �������� �� ������ ��� ����
    sub_filter '<head><title>Index of $uri</title></head>' '';
    sub_filter '<body>' '';
    sub_filter '<h1>Index of $uri</h1><hr>' '';
    sub_filter '<hr></body>' '';
    sub_filter '</html>' '';
    sub_filter_once on; # �������� ����������� ������������ ��������
    add_before_body /.html/header.html; # ���������� "�����" �����
    add_after_body /.html/footer.html; # ���������� "������" �����
        }
        
}
`
![image](https://user-images.githubusercontent.com/54883747/195396817-4f758497-ffaf-4253-9d1a-0728f052fb4c.png)

**Comment by JoCat** [comment]
Тут хз, я тебе ничем не помогу, я и сам не понял почему такое там встречается

**Comment by IVKLD** [comment]
Ок, тогда попробую решить и сюда написать, если получится.

**Comment by JoCat** [comment]
Можешь попробовать поиграться с limit_conn, мб поможет
https://nginx.org/ru/docs/http/ngx_http_limit_conn_module.html

**Comment by IVKLD** [comment]
Без б

**Comment by JoCat** [comment]
UPD. Проблема наблюдается при использовании cloudflare
